### ISSUE TITLE
Share bootloader keys test between Model 01 and Model 100?

### ISSUE THREAD

**Issue by tlyu** [keyboardio/attiny_i2c_bootloader#7]
Should the bootloader possibly share the key checking code between Model 01 and Model 100? It looks like the hardware might be similar enough.

That would allow an immediate application start on the Model 01, and have the added benefit of avoiding repeated firmware flashing if the flasher sketch is accidentally restarted.

Maybe the code size was originally too tight to both do that and the Model 01-specific initialization?

**Comment by obra** [comment]
The key tests post-date the Model 01. I don't think we're all that likely to push a bootloader update for the Model 01, but it wouldn't be bad to have the feature on that side of things.
